### PR TITLE
[Draft, do not merge] test multiple time periods

### PR DESCRIPTION
**Pull request by solderq35**
## Main TODO
Maybe should separate this out to separate GitHub Issues. Not exhaustive
- [x] "Cancel" button on edit menu was not tested very thoroughly for the timestamps, needs bug fixes
  - If you saved some timestamps earlier (clicked "save time period" > "ok"), then open edit menu again and then click "cancel", the counter on the "save time period" goes all the way to zero
- [x] Multiple time period chart bug where after comparing more than one time period of a single building, then going to the map page and comparing that same building with another will result in the extra time period chart(s) showing up. The chart is fixed on page refresh
- [x] Labels on the charts needs work, see comments on building_compare_mod.js file. Need to handle (both on first page load and after editing the chart):
  - One building, multiple time periods (priority)
  - One building, same time period
  - Multiple Buildings, same time period
    - [x] Need energy type labels (pointstring) for multiple time periods graph, after we implement ability to change meters 
- [x] Support different meters per building (say if you want to compare a particular meter on one building with multiple time periods)
  - If you look at the current edit_card.vue code for regular buildings, technically this is for *meter groups*
- [x] Support different energy types (Electricity, Steam. etc)
  - Changed to immediately take user to comparison page for single building comparison. Only electricity is supported for multiple building comparison
- [x] Implement moving the charts left to align by day of the month (So December 2 and October 2, for instance, start on same point on X-axis)
- [x] Implement tooltips (hovering mouse over graph at specific points) that *are* accurate to the actual dates. Might need to track the actual dates separately depending on how we move the charts left
  - See src\store\chart_modifiers\line_bar\accumulated_real.js for current implementation of tooltips
- [x] Add some kind of block UI for the edit menu, showing start and end dates for previously saved time periods (refer to Figma). Should support deleting time periods from the edit menu UI, and maybe editing previously submitted time periods as well
  - [x] Block UI with start and end dates for previously saved time periods
  - [x] Delete functionality. X button per saved time block. No edit functionality needed.
- [x] Add a link to the compare menu for same building, multiple time periods from the individual building (non compare) pages
- [x] (Stretch goal): Check for mobile compatibility before merging, due to 600px media queries for mobile screens. Especially on map_prompt.vue file

## Issue
https://github.com/OSU-Sustainability-Office/energy-dashboard/issues/278

### CODE REVIEW

**Comment by solderq35** [comment]
TODO:
- Support multiple charts of the same building properly (not just the hacky way it's currently supported by block.module.js's loadDefault function)
- Probably need to rework the whole block / chart data structure to support multiple time periods per chart. May require backend work or updating API, not sure
- Fix bug with chart labels resetting after you change the time period with edit menu
image

**Comment by solderq35** [comment]
chart labels issue: https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/1ac2954aacb208f02743410f3cf9b079f6f01eff/src/components/view/modals/edit_card.vue#L372

**Comment by solderq35** [comment]
image

Was able to figure out how to properly align data from different months. 

chart.module.js file makes API call to get data via meter_Groups.module.js

So as far as just getting the data to be from different time periods we can do all of that in chart.module file in theory (although it may be better in the long run to rework block.module.js).

Just need to figure out how to support more than 3 charts without vuex error, and how to connect the different time settings in chart.module.js to the edit_card form

**Comment by solderq35** [comment]
## Screenshots

image

image

image

image

## Instructions

As shown in above screenshots, adjust start and end dates and then click "Save Time Period". Repeat for all time periods you want to save, then click "OK" at the end.

## TODO
Maybe should separate this out to separate GitHub Issues. Not exhaustive
- "Cancel" button on edit menu was not tested very thoroughly for the timestamps, needs bug fixes
  - If you saved some timestamps earlier (clicked "save time period" > "ok"), then open edit menu again and then click "cancel", the counter on the "save time period" goes all the way to zero
- Labels on the charts needs work, see comments on building_compare_mod.js file
- Support different meters per building (say if you want to compare a particular meter on one building with multiple time periods)
  - If you look at the current edit_card.vue code for regular buildings, technically this is for *meter groups*
- Support different energy types (Electricity, Steam. etc)
- Implement moving the charts left to align by day of the month (So December 2 and October 2, for instance, start on same point on X-axis)
- Implement tooltips (hovering mouse over graph at specific points) that *are* accurate to the actual dates. Might need to track the actual dates separately depending on how we move the charts left
- Add some kind of block UI for the edit menu, showing start and end dates for previously saved time periods (refer to Figma). Should support deleting time periods from the edit menu UI, and maybe editing previously submitted time periods as well

**Comment by s-egge** [comment]
Before
---
image


After
---
image

image

image


I was able to get the data shifted left by mapping the x-values of the charts to the x-values of the largest chart, similar to what was done before in chart.module but now it's done in chartController.vue. 

The original x-values of the charts are saved in a new variable in their data so that they can be used in linechart.js in order to display the proper date when hovering.

image


The x-axis labels, bottom chart label, and line labels still need to be fixed, along with the issues mentioned above in the TODO.

**Comment by s-egge** [comment]
Compare Multiple Time Periods Button
---
image
image

After Pressing The Button
---
image
Notice the change in URL between the first/second/third picture. After pressing the button, the multiple time period option shows up in the edit block.

Bugs
---
The buttons on the right of the navbar are still visible until the page is refreshed:
image
I've tried a few things to fix this (watching $route, using beforeRouteUpdate, etc.). The only thing that worked was moving the `v-if="!otherView"` from the `menu` tag to the `bar` tag above it. I didn't leave this in as I'm not familiar with the public/users views being referenced here: https://github.com/OSU-Sustainability-Office/energy-dashboard/blob/e0f422f3d14cb455dfbf5f32a7394b91d5e01ed8/src/components/view/navdir.vue#L92


After refreshing the page and pressing the back button in the browser (both with and without moving the `v-if` statement), the navbar is no longer visible on the `building` page until it is refreshed:
image

**Comment by s-egge** [comment]
Before
---
image

After
---
image
image

The time period comparison option will only display if there are less than two buildings selected (so 0 or 1 building). 

image

The compareStories array is passed to `map_prompt.vue` via props in order to check the number of buildings selected. I set the command to 't' but it isn't currently needed to be checked, since the `else` statement in `map.vue's` showComparison function handles the logic correctly whether it's one building or several.

**Comment by s-egge** [comment]
Comparing more than one building name fix
---
I added an if-statement to prevent a building name being reset when changing the time period for comparing more than one building, see the comments in edit_card.vue on the last commit. I tested with several different buildings/combos and it seems to fix it, but more testing is welcome

image

Multiple time period label update
---
image
image

I updated the labels at the top of the multiple time period comparison chart and added a check to remove the bottom label if there is more than one chart for a single building. The x-axis labels still need to be updated. 

I also moved the majority of the formatting logic for multiple time periods into one function since it was getting large and starting to clutter the updateChart function

**Comment by s-egge** [comment]
Multiple Time Period X-Axis Labels Fix
---
image
image

The x-axis labels will only change if there are multiple time period charts. We might want to check with Brandon and Ross to see if this will work for the labeling, but it should be easy enough to change it now that the logic is there.

**Comment by solderq35** [comment]
I'll clarify here later what my last 2 commits did when I have time, otherwise read comments in code

**Comment by solderq35** [comment]
> ## Multiple time period label update
> image image
> 
> I updated the labels at the top of the multiple time period comparison chart and added a check to remove the bottom label if there is more than one chart for a single building. The x-axis labels still need to be updated.
> 
> I also moved the majority of the formatting logic for multiple time periods into one function since it was getting large and starting to clutter the updateChart function

For the second image there (multiple time periods, one building), I would suggest adding energy types, so that the labels go something like "October 1 to November 1, Net Energy Usage)" (example), in order to support multiple meters (and meter types) in the future.

**Comment by s-egge** [comment]
Compare Meters Other Than Electricity and Measurements other than Total
---
image

image

It's not possible to change the Meter type and Measurement. If time periods are added and the Meter/Measurement is changed, all data will be pulled based on whatever the Meter/Measurement is when "Ok" is hit. Different Meter/Measurement combos cannot be compared to each other right now. 

image

The card name will now also change based on the Meter type, this updates when in both compare view and single building view.

**Comment by solderq35** [comment]
Stuff we didn't implement / maybe for future:
- Multiple energy types for multiple building comparison (compare 2 steam buildings). Same for multiple meters or measurements for multiple building comparison
- Map popup for single building comparison
- Download tab / sharing feature on comparison (either single or multiple building)

**Comment by solderq35** [comment]
TODO: 
- Remove any code comments that are just about this PR and not something we need in the codebase permanently
- Remove any console.log statements that weren't already there
- Check for any other bugs

Then we can merge PR and send email to Brandon / Ross with screenshots

**Review by s-egge — APPROVED** [review]
The changes look good to me, I don't see any extra console.logs, irrelevant comments, or bugs.

**Pull request merged**
