### PR TITLE
Pacific Power Recent Data GET Endpoint

### PR DESCRIPTION
**Pull request by solderq35**
## Related Issue
- https://github.com/OSU-Sustainability-Office/automated-jobs/issues/42

## Changes
SQL code (`backend\dependencies\nodejs\models\pacific_power_data.js`)
- Unix timestamp, pacific power meter ID for each pacific power meter, in the past 3 days. If there are multiple results per meter, get the most recent one. Sort final list of results by timestamp ascending (earliest first).
- You can test the SQL query in SQL workbench with some other arbitrary timestamp (like from March 3 or something) to confirm at least 1 timestamp will be different

JS Code (`backend\dependencies\nodejs\models\pacific_power_data.js`)
- See https://playcode.io/1804875 for quick testing

## Testing
- Run backend locally (`sam local start-api` from backend directory)
- Visit http://localhost:3000/pprecent
image
- See earlier sections for other ways to test SQL and JS code

## TODO
- Update PacificPower scraper in automated-jobs repo to handle uploading missing data when detected (based on pprecent endpoint), handle case of getting previous month's data
- Cloudwatch alerts for new meters (reference ppRecent)
  - Or move this to blacklisted meters data structure
  - May cause false alarms in rare case that a meter is down for more than 3 days and then up again
- 3 days is just a placeholder value, might raise this depending on performance (needs testing)
  - Just need *some* kind of upper limit to prevent infinite scaling as more data is added (will probably get better after pacific power meter blacklist is implemented)

### CODE REVIEW

**Comment by solderq35** [comment]
I tried extending the time window from 3 to 7 days, and the performance didn't seem that much worse (maybe about 1.5 to 2x slower at worst, and still faster than the allbuildings API endpoint).

## Local backend testing screenshots
- pprecent endpoint, 3 days time window (Duration: 445 ms)
image

- pprecent endpoint, 7 days time window (Duration: 642 ms)
image

- allbuildings endpoint (Duration: 940 ms)
image

## TODO
- Probably won't do much more work in energy-dashboard repo for this, and move to the automated-jobs webscraper side. I picked 7 days time window as I don't think we would ever need to upload more than a week's missing data (and that may still be overkill), so we'll adjust the time window if needed based on how the webscraper stuff goes

**Comment by solderq35** [comment]
Marking this as ready for review. Think I will keep the 7 day timeframe because there were cases where the data was out of date for 2 days or more for one reason or another, and I have updated my [missing data webscraper PR](https://github.com/OSU-Sustainability-Office/automated-jobs/pull/50) to check for up to 7 days prior via while loops

**Review by s-egge — APPROVED** [review]
Looks good to me and works as expected.

**Comment by solderq35** [comment]
Follow-up task (future PR): https://github.com/OSU-Sustainability-Office/automated-jobs/issues/51

**Comment by solderq35** [comment]
Updated to list data from past 7 days per meter. Duplicate values (same meter ID + time stamp as an existing value) are skipped

Also, upload with same meter ID + time stamp as an existing value now returns 400 error

**Comment by solderq35** [comment]
Fixed merge errors from exclusion energy dashboard PR, will fix merge errors for automated-jobs repo later

**Review by s-egge — APPROVED** [review]
Looks good, both of the new endpoints are working as expected.

**Pull request merged**
